name = "ModeratelyVanilla"
author = "TheTheoros"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cb7f3f71c5ec8ea997a30adb0d52d712613198a96569d0b7c351af5a4f97ef4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
