name = "ModeratelyVanilla"
author = "TheTheoros"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2da08018a894539eb7b07d8ee0658870a390bc258e78f570054cc19c82918b8a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
