#Better Party HUD settings
#Thu Oct 01 20:57:21 EDT 2026
color_mode=STANDARD
hud_layout=HORIZONTAL
inventory_button_icon=ADVENTURERS
inventory_button_offset_x=24
inventory_button_offset_y=0
inventory_button_scale=100
inventory_button_visible=true
manual_order=badc17c2-186d-47f6-964b-7c349827a53d,5e633e4b-3365-4f64-b5ff-432965d27253
member_locator_intensity=100
member_locator_mode=OFF
position_x=10
position_y=12
scale=100
show_faces=false
show_hunger=false
show_legend=false
show_level=true
show_offline_players=true
sort_mode=PARTY_ORDER
