		[types.stone_type.burnt]
			sooty_stone = true

		[types.stone_type.unearthed]
			phyllite = true
			slate = true
			gabbro = true
			granodiorite = true
			rhyolite = true
			limestone = true
			conglomerate = true
			dacite = true
			dolomite = true

		[types.stone_type.caverns_and_chasms]
			sugilite = true
			cylindrite = true
			cassiterite = true
			rhyolite = true

		[types.stone_type.incision]
			clottage = true
			weatherrack = true
			goreshed = true

		[types.stone_type.netherman]
			samsonit = true

		[types.stone_type.sulfurnitre]
			brimsand = true

		[types.stone_type.spelunkers_charm]
			permafrost = true
			dunestone = true
			wildstone = true

		[types.wood_type.burnt]
			smoldering_bamboo = true

		[types.wood_type.burnt_additions]
			smoldering_soul = true
			soul_tempered = true

		[types.wood_type.minecraft]
			pale_oak = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.spawn]
			rotten = true
			date = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.cluttered]
			willow = true
			flowering_willow = true
			poplar = true
			flowering_poplar = true
			crabapple = true
			flowering_crabapple = true
			sycamore = true
			fluorescent_maple = true
			blue_mushroom = true
			red_mushroom = true

		[types.leaves_type.minecraft]
			pale_oak = true

		[types.leaves_type.spawn]
			date = true

		[types.leaves_type.cluttered]
			willow = true
			flowering_willow = true
			poplar = true
			flowering_poplar = true
			crabapple = true
			flowering_crabapple = true
			sycamore = true
			fluorescent_maple = true
			flowering_fluorescent_maple = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.woodworks]
			bookshelf = true
			chiseled_bookshelf = true
			boards = true
			chest = true
			trapped_closet = true
			closet = true
			ladder = true
			beehive = true
			trapped_chest = true

		[entries.stone_type.waystones]
			waystone = true

		[entries.leaves_type.woodworks]
			leaf_pile = true
