[bookshelves]
	#The number of blocks in the X-position that the enchanting table can detect chiseled bookshelves. Each 'row' can hold up to 96 books. If you have many enchantments, you may need to increase this value to provide more space.
	# Default: 2
	# Range: 2 ~ 8
	bookshelfSearchX = 2
	#The number of blocks in the Y-position that the enchanting table can detect chiseled bookshelves. Each 'row' can hold up to 96 books. If you have many enchantments, you may need to increase this value to provide more space.
	# Default: 3
	# Range: 1 ~ 8
	bookshelfSearchY = 3
	#The number of blocks in the Z-position that the enchanting table can detect chiseled bookshelves. Each 'row' can hold up to 96 books. If you have many enchantments, you may need to increase this value to provide more space.
	# Default: 2
	# Range: 2 ~ 8
	bookshelfSearchZ = 2

[enchantingtable]
	#Allow enchantments to be removed in the enchanting table.
	allowEnchantmentRemoval = true
	#If enabled, enchantments that have not been found will be obfuscated in the enchanting table.
	obfuscateLockedEnchantments = true
	#If enabled, Ancient Books are no longer required to unlock enchantments at the enchanting table. Enchantments still cost experience and materials as usual.
	disableAncientBookRequirement = false

[enchantedbooks]
	#Choose whether enchanted books should be removed completely or replaced with ancient books. Ancient books still spawn as normal.
	#Allowed Values: REPLACE, REMOVE
	enchantedBookLootMode = "REPLACE"
	#If enabled, vanilla enchanted books will not appear in villager trades.
	disableEnchantedBookTrades = true
