#Adds badge to mod in this format "modid=badge1, badge2"
mod_badges = []
#Make mods apear under another mod in this format "parenModId=childId1, childId2", add ! at the beginning of parentId to prevent creating a fake parent
mod_parents = []

[main]
	#Allowed Values: ASCENDING, DESCENDING
	sorting = "ASCENDING"
	#Makes list more compacted
	compact_list = true
	#Allowed Values: CLASSIC, REPLACE_REALMS, SHRINK, SHRINK_LEFT, ICON
	mods_button_style = "REPLACE_REALMS"
	#Allowed Values: REPLACE, INSERT, ICON
	game_menu_button_style = "REPLACE"
	#Allowed Values: TITLE_SCREEN, MODS_BUTTON, TITLE_SCREEN_AND_MODS_BUTTON, NONE
	mod_count_location = "TITLE_SCREEN"
	#Shows secret mod count translations defined by modmenu.mods.MOD_COUND.secret
	easter_eggs = true
	#Makes java mod have random colors
	random_java_colors = false
	#Make mod names translatable defining by modmenu.nameTranslation.modid
	translate_names = true
	#Make mod descriptions translatable defining by modmenu.descriptionTranslation.modid
	translate_descriptions = true
	#Shows config button above mod icon on the left
	quick_configure = true
	#Modifies title screen, if false will be neoforge default with default mods button
	modify_title_screen = true
	#Changes pause screen's button position and replaces neoforge's mods button with better modlist's one
	modify_game_menu = true
	#Will only show mods with config available
	config_mode = false
	#Allows to edit mod badges and parents ingame by dragging or button
	editor_mode = false
	#Disables drag and drop mods adding
	disable_drag_and_drop = true
	#Will use catalogue's icon if present
	use_catalogue_icon = true

[hide]
	#Shows mods with library badge
	show_libraries = false
	#Hides links of the mod
	hide_mod_links = false
	#Hides mod's license
	hide_mod_license = false
	#Hides mod's badges
	hide_badges = false
	#Add id of the badge to hide it
	hide_badge = []
	#Hides mod's credits
	hide_mod_credits = false
	#Hides mod's config button
	hide_config_buttons = false
	#Hides search bar and drag and drop text, also moves mod's icon up
	hide_screen_top = false
	#Add modid of the mod to hide it from the modlist
	hidden_mods = ["minecraft", "narrus_yeetus_no_error", "neoforge", "rebind_narrator", "reeses_sodium_options", "placebo", "toastcontrol", "controlling", "searchables", "distraction_free_recipes", "jei", "mezz_config", "txnilib", "item_obliterator", "necronomicon", "attributefix", "bookshelf", "prickle", "maxhealthfix", "burnt_coldsweat_compat", "cloth_config", "cold_sweat", "geckolib", "globalpacks", "mr_lukis_strongholds", "resourcepackoverrides", "mr_stellarity_lite", "mr_stellarityxyung", "yungsapi", "betterendisland", "witherreincarnated", "betteradvancedtooltips", "kubejs", "rhino", "flintrequired", "durabilityreworked", "architectury", "nerb", "octolib", "platform", "vanillabackport", "sable", "treephysicsnoshiftmode", "reliable_replacer", "moonlight", "everycomp", "stonezone", "additionalplacements", "baguettelib", "better_party", "chat_heads", "chatanimation", "chatimage", "emotecraft", "emotetweaks", "voicechat", "voicechat_api", "twemoji", "voicemessages", "yet_another_config_lib_v3", "creeperfireworks", "unearthed", "dynamic_asset_generator", "excavated_variants", "probejs", "helpfulcampfires", "jemscampfires", "firestarters", "bucketlib", "betterdays", "bettersafebed", "darksleep", "stevesrealisticsleep", "entity_model_features", "entity_texture_features", "hackersandslashers", "owo", "player_animation_library", "toucanlib", "cirrus", "blueprint", "anvilrepairing", "collective", "durabilitytooltip", "fixedanvilrepaircost", "supermartijn642configlib", "almostunified", "audrops", "alternate_current", "balm", "betterworldloadingnf21", "cubes_without_borders", "dimensionalsyncfixes", "duplicationless", "entityculling", "fastsuite", "ferritecore", "flerovium", "fzzy_config", "kotlinforforge", "immediatelyfast", "ivp", "kiwi", "konkrete", "lithostitched", "midnightlib", "modelfix", "modernfix", "modernworldcreation", "moreculling", "nanny", "netherportalfix", "overflowingbars", "puzzleslib", "particle_core", "redirected", "resourcefulconfig", "simple_snowy_fix", "spark", "structure_layout_optimizer", "toofast", "biomespawnpoint", "snowrealmagic", "stormiespiders", "aaa_particles", "archaion", "accessories_compat_layer", "tclayer", "cclayer", "alfinolib", "mr_epic_structuresjungletemples", "mr_epic_structureswitchhuts", "mr_epic_structuresdungeons", "mr_epic_structuresvillages", "fdlib", "incision", "mr_lukis_ancientcities", "mr_lukis_crazychambers", "mr_lukis_woodlandmansions", "mobspawncontroller", "mmr", "moogs_structures", "sodiumdynamiclights", "raidsenhanced", "curios", "isleweaver", "the_beyond", "structurify", "teallib", "bettercaves", "betterfortresses", "betteroceanmonuments", "skinlayers3d", "abridged", "appleskin", "archers_expansion", "armor_model_api", "artifactdelight", "betterbeds", "boatbreakfix", "bridgingmod", "bundleapi", "caelus", "celestial_artifacts", "celestial_core", "commonnetworking", "critical_strike", "deuf", "diagonalfences", "diagonalwalls", "diagonalwindows", "do_a_barrel_roll", "dummmmmmy", "elysium_api", "endersdelight", "explosiveenhancement", "coolrain", "fastitemframes", "fastpaintings", "gtalike_teleport", "hoporp", "hopour", "geophilic", "geophilic_backport", "iceberg", "kleeslabs", "l2library", "legendarytooltips", "lodestone", "lootr", "mes", "minersdelight", "more_rpg_classes", "spell_engine", "mynethersdelight", "neat", "notenoughanimations", "nullscape", "particlerain", "particular", "pickupnotifier", "playeranimator", "polytone", "prism", "puffish_biome_dither", "puffish_skills", "ranged_weapon_api", "rolling_down_in_the_deep", "runes", "shield_api", "smarterfarmers", "sparkweave", "spell_power", "structure_pool_api", "xpbook", "actualfishing", "alloy_smelter", "unionlib", "unionlib_potionfluid", "inhousegunspolymer", "amplified_nether", "sulfurnitre", "armor_3d", "boids", "diversity", "faewulf_lib", "mapdistancefix", "revotedwildfire", "shulkerboxtooltip", "tightfire", "charms", "abnormals_delight", "bards_rpg", "bettertridents", "cluttered", "crawl", "delightfulbackport", "dumplings_delight", "fwa", "fancytoasts", "ftblibrary", "ftbquests", "ftbteams", "jadensnetherexpansiondelight", "leavemybarsalone", "lootr_liason", "neobeefix", "obe", "passiveshield", "presencefootsteps", "puddleflood", "connectiblechains", "rottencreatures", "spelunkers_charm", "terrablender", "uiquest", "undead_unleashed", "mr_vb_compat", "voidfog", "wildfire_gender", "cyclopscore", "mod_menu"]
	#Add modid of the mod to hide its config
	hidden_configs = ["sodium", "emi", "treephysics", "farmersdelight", "sleep_tight", "villagerretaliation", "betterinventory", "yigd", "accessories", "immersiveenchanting", "spawn", "archers", "artifacts", "icarus", "netherexp", "paladins", "rogues", "waystones", "wizards", "solcarrot", "toms_storage"]
	#deprecated
	library_list = []

	#deprecated
	[hide.disable_default_badges_section]
		disable_default_badges_all = false
		disable_default_badges = []

[count]
	#Makes hidden mods count added to the total mods count
	count_hidden_mods = false
	#Makes childrens count get added to the total mods count
	count_children = false
	#Makes libraries count get added to the total mods count
	count_libraries = false
